---
pipeline:
  fetch:
    - unit_test: deploy
    - build
edges:
  - build: deploy
profiles:
  fetch:
    script: ./scripts/fetch_and_tar_repo.sh
    output: scm_artifact.tar
  unit_test:
    input: scm_artifact.tar
    script: ./scripts/run_unit_tests.sh
  build:
    input: scm_artifact.tar
    script: ./scripts/build_webpage.sh
    output: build_artifact.tar
  deploy:
    input: build_artifact.tar
    script: ./scripts/deploy_package.sh
  default:
    script: ./scripts/fetch_and_tar_repo.sh
