plan:
- fetch
- first
- second
- last

profiles:
  fetch:
    script: bin/fetch
  first:
    script: bin/first
  second:
    script: bin/second
  last:
    script: bin/last


pipeline:
  fetch:
   - first: last
   - second

edges:
  - second: last