hooks:
  pre_setup: gem install minitest

plan:
- fetch
- first
- second
- last

profiles:
  fetch:
    tests:
      - ruby poker_test.rb
    #script: bin/fetch
  first:
    tests:
      - ruby poker_test.rb
    #script: bin/first
  second:
    tests:
      - ruby poker_test.rb
    #script: bin/second
  last:
    tests:
      - ruby poker_test.rb
    #script: bin/last


pipeline:
  fetch:
   - first: last
   - second

edges:
  - second: last