---
pipeline:
  fetch:
    - unit_test: deploy
    - build
edges:
  - build: deploy
profiles:
  fetch:
    script: ./scripts/fetch.sh
    output: 
      - scm_artifact.tar
  unit_test:
    input: 
      - scm_artifact.tar
    script: ./scripts/unit_test.sh
  build:
    input: 
      - scm_artifact.tar
    script: ./scripts/build.sh
    output: 
      - build_artifact.tar
  deploy:
    input: 
      - build_artifact.tar
    script: ./scripts/deploy.sh
    environment:
      AWS_ECR_REPO: 418216297797.dkr.ecr.us-east-1.amazonaws.com
      DOCKER_IMAGE: predix-ci
      # SOLANO_API_KEY:  set in Predix CI UI
      # AWS_SECRET_ACCESS_KEY:  set in Predix CI UI
      # AWS_ACCESS_KEY_ID:  set in Predix CI UI
  default:
    script: dev/null
